"""Integration tests for the API endpoints using PostgreSQL."""

import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient
from langchain_core.documents import Document
from testcontainers.postgres import PostgresContainer

from ebook_rag_explorer.adapters.embedding.sentence_transformer_adapter import (
    SentenceTransformerAdapter,
)
from ebook_rag_explorer.adapters.llm.langchain_llm_adapter import LangChainLLMAdapter
from ebook_rag_explorer.adapters.retrieval.cross_encoder_reranker import (
    CrossEncoderReranker,
)
from ebook_rag_explorer.adapters.retrieval.postgres_retriever import PostgresRetriever
from ebook_rag_explorer.adapters.vectorstore.postgres_adapter import PostgresAdapter
from ebook_rag_explorer.api.app import create_app
from ebook_rag_explorer.config import Settings, reset_settings
from ebook_rag_explorer.services.chunking_service import ChunkingService
from ebook_rag_explorer.services.indexing_service import IndexingService
from ebook_rag_explorer.services.retrieval_service import RetrievalService


@pytest.fixture(scope="module")
def postgres_container():
    """Create a PostgreSQL container with pgvector."""
    with PostgresContainer("docker.io/pgvector/pgvector:pg16") as postgres:
        postgres.exec(f"psql -U {postgres.username} -d {postgres.dbname} -c 'CREATE EXTENSION IF NOT EXISTS vector;'")
        yield postgres


@pytest.fixture
def db_url(postgres_container):
    """Get the async database URL."""
    sync_url = postgres_container.get_connection_url()
    import re
    match = re.match(r"postgresql\+psycopg2://(.+):(.+)@(.+):(\d+)/(.+)", sync_url)
    if match:
        user, password, host, port, db = match.groups()
        async_url = f"postgresql://{user}:{password}@{host}:{port}/{db}"
    else:
        async_url = sync_url.replace("postgresql+psycopg2://", "postgresql://")
    return async_url


@pytest.fixture(autouse=True)
def reset_dependencies():
    """Reset global dependencies before each test."""
    from ebook_rag_explorer.api import dependencies

    dependencies._vector_store = None
    dependencies._embedder = None
    dependencies._retrieval_service = None
    reset_settings()
    yield


@pytest.fixture
def mock_embedder():
    """Create a mock embedder that returns predictable embeddings."""
    embedder = MagicMock(spec=SentenceTransformerAdapter)

    def embed_documents_side_effect(texts):
        return [[0.1, 0.2, 0.3] + [0.0] * 381 for _ in texts]

    def embed_query_side_effect(text):
        return [0.1, 0.2, 0.3] + [0.0] * 381

    embedder.embed_documents.side_effect = embed_documents_side_effect
    embedder.embed_query.side_effect = embed_query_side_effect
    return embedder


@pytest.fixture
def mock_llm():
    """Create a mock LLM."""
    llm = MagicMock(spec=LangChainLLMAdapter)
    llm.is_available = True
    llm.generate.return_value = "This is a test answer generated by the LLM."
    llm.agenerate.return_value = "This is a test answer generated by the LLM."
    return llm


@pytest.fixture
def mock_reranker():
    """Create a mock reranker."""
    reranker = MagicMock(spec=CrossEncoderReranker)

    def mock_rerank(query, documents, top_n):
        result = []
        for i, doc in enumerate(documents[:top_n]):
            doc_copy = Document(
                page_content=doc.page_content,
                metadata={**doc.metadata, "rerank_score": 0.9 - (i * 0.1)},
            )
            result.append(doc_copy)
        return result

    reranker.rerank.side_effect = mock_rerank
    return reranker


def create_test_app(db_url: str, mock_embedder, mock_llm, mock_reranker):
    """Create a test FastAPI app with mocked dependencies."""
    from ebook_rag_explorer.api import dependencies

    settings = Settings(
        database_url=db_url,
        embedding_model="sentence-transformers/all-MiniLM-L6-v2",
        reranker_model="cross-encoder/ms-marco-MiniLM-L-6-v2",
        llm_provider="openai",
        llm_model="gpt-4o-mini",
        chunk_size=100,
        chunk_overlap=20,
        retrieval_top_k=5,
        rerank_top_n=3,
    )

    # Set up dependencies
    vector_store = PostgresAdapter(db_url)
    dependencies.set_vector_store(vector_store)
    dependencies.set_embedder(mock_embedder)

    retriever = PostgresRetriever(vector_store, mock_embedder)
    retrieval_service = RetrievalService(
        retriever=retriever,
        reranker=mock_reranker,
        llm=mock_llm,
        retrieval_top_k=5,
        rerank_top_n=3,
    )
    dependencies.set_retrieval_service(retrieval_service)

    app = create_app(settings)
    return app, vector_store


async def init_schema(adapter: PostgresAdapter):
    """Initialize the database schema."""
    pool = await adapter._get_pool()
    async with pool.acquire() as conn:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS books (
                id VARCHAR(255) PRIMARY KEY,
                title VARCHAR(500),
                author VARCHAR(255),
                format VARCHAR(50),
                collection_id VARCHAR(255),
                metadata JSONB DEFAULT '{}',
                chunk_count INTEGER DEFAULT 0,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            )
        """)

        await conn.execute("""
            CREATE TABLE IF NOT EXISTS documents (
                id SERIAL PRIMARY KEY,
                chunk_id VARCHAR(255) NOT NULL UNIQUE,
                book_id VARCHAR(255) REFERENCES books(id) ON DELETE CASCADE,
                collection_id VARCHAR(255),
                content TEXT NOT NULL,
                embedding VECTOR(384),
                search_vector tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('english', COALESCE(content, '')), 'A')
                ) STORED,
                chunk_index INTEGER DEFAULT 0,
                total_chunks INTEGER DEFAULT 0,
                source_metadata JSONB DEFAULT '{}',
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            )
        """)

        await conn.execute("CREATE INDEX IF NOT EXISTS idx_books_collection ON books(collection_id)")
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_documents_book_id ON documents(book_id)")
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_documents_collection ON documents(collection_id)")
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_documents_embedding ON documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 10)")

        await conn.execute("""
            CREATE OR REPLACE VIEW collection_stats AS
            SELECT
                collection_id AS id,
                collection_id AS name,
                COUNT(DISTINCT book_id) AS book_count,
                COUNT(*) AS chunk_count
            FROM documents
            WHERE collection_id IS NOT NULL
            GROUP BY collection_id
        """)


class TestHealthEndpoint:
    """Tests for the health check endpoint."""

    def test_health_check(self, db_url, mock_embedder, mock_llm, mock_reranker):
        """Test the health check endpoint."""
        app, _ = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)

        response = client.get("/health")
        assert response.status_code == 200
        assert response.json()["status"] == "healthy"


class TestIndexEndpoint:
    """Tests for the index endpoint."""

    async def test_index_pdf_success(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test successfully indexing a PDF file."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)

        # Mock fitz for PDF parsing
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book", "author": "Test Author"}
            mock_doc.__len__ = MagicMock(return_value=1)

            mock_page = MagicMock()
            mock_page.get_text.return_value = "This is test content for the PDF."

            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)

            mock_fitz.return_value = mock_doc

            # Create test file
            with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
                tmp.write(b"dummy pdf content")
                tmp_path = Path(tmp.name)

            client = TestClient(app)

            with open(tmp_path, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                )

            assert response.status_code == 200
            data = response.json()
            assert data["format"] == "PDF"
            assert data["title"] == "Test Book"
            assert "book_id" in data

            # Cleanup
            tmp_path.unlink()

    def test_index_unsupported_format(self, db_url, mock_embedder, mock_llm, mock_reranker):
        """Test indexing an unsupported file format."""
        app, _ = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)

        response = client.post(
            "/api/index",
            files={"file": ("test.txt", b"some text content", "text/plain")},
        )

        assert response.status_code == 400
        assert "Unsupported file format" in response.json()["detail"]


class TestSearchEndpoint:
    """Tests for the search endpoint."""

    async def test_search_success(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test successful search."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)

        # Mock fitz for indexing
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)

            mock_page = MagicMock()
            mock_page.get_text.return_value = "Python programming is great for data science."

            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)

            mock_fitz.return_value = mock_doc

            with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
                tmp.write(b"dummy")
                tmp_path = Path(tmp.name)

            client = TestClient(app)

            with open(tmp_path, "rb") as f:
                client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                )

            tmp_path.unlink()

        # Now search
        response = client.post(
            "/api/search",
            json={"query": "What is Python used for?"},
        )

        assert response.status_code == 200
        data = response.json()
        assert "query" in data
        assert "answer" in data
        assert "sources" in data


class TestBooksEndpoint:
    """Tests for the books endpoint."""

    async def test_list_books_empty(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test listing books when none are indexed."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)

        # Clear any existing data
        await vector_store.clear()

        client = TestClient(app)
        response = client.get("/api/books")

        assert response.status_code == 200
        assert response.json() == []

    async def test_delete_book_not_found(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test deleting a non-existent book."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)

        client = TestClient(app)
        response = client.delete("/api/books/non-existent-id")

        assert response.status_code == 404


class TestCollectionsEndpoint:
    """Tests for the collections endpoint."""

    async def test_list_collections_empty(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test listing collections when none exist."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)
        await vector_store.clear()

        client = TestClient(app)
        response = client.get("/api/collections")

        assert response.status_code == 200
        assert response.json() == []

    async def test_index_with_collection(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test indexing a document with a collection."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)
        await vector_store.clear()

        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)
            mock_page = MagicMock()
            mock_page.get_text.return_value = "Content"
            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)
            mock_fitz.return_value = mock_doc

            with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
                tmp.write(b"dummy")
                tmp_path = Path(tmp.name)

            client = TestClient(app)

            with open(tmp_path, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                    data={"collection_id": "TestCollection"},
                )

            assert response.status_code == 200
            tmp_path.unlink()

        # List collections
        response = client.get("/api/collections")
        assert response.status_code == 200
        collections = response.json()
        assert len(collections) == 1
        assert collections[0]["id"] == "testcollection"

    async def test_delete_collection_not_found(self, db_url, mock_embedder, mock_llm, mock_reranker, postgres_container):
        """Test deleting a non-existent collection."""
        app, vector_store = create_test_app(db_url, mock_embedder, mock_llm, mock_reranker)
        await init_schema(vector_store)

        client = TestClient(app)
        response = client.delete("/api/collections/non-existent")

        assert response.status_code == 404


# Run with: pytest tests/integration/test_api.py -v
