"""Integration tests for the API endpoints."""

import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient
from langchain_core.documents import Document

from ebook_rag_explorer.adapters.embedding.sentence_transformer_adapter import (
    SentenceTransformerAdapter,
)
from ebook_rag_explorer.adapters.llm.langchain_llm_adapter import LangChainLLMAdapter
from ebook_rag_explorer.adapters.retrieval.chroma_retriever import ChromaRetriever
from ebook_rag_explorer.adapters.retrieval.cross_encoder_reranker import (
    CrossEncoderReranker,
)
from ebook_rag_explorer.adapters.vectorstore.chroma_adapter import ChromaAdapter
from ebook_rag_explorer.api.app import create_app
from ebook_rag_explorer.config import Settings, reset_settings
from ebook_rag_explorer.services.chunking_service import ChunkingService
from ebook_rag_explorer.services.indexing_service import IndexingService
from ebook_rag_explorer.services.retrieval_service import RetrievalService


@pytest.fixture(autouse=True)
def reset_dependencies():
    """Reset global dependencies before each test."""
    from ebook_rag_explorer.api import dependencies
    from ebook_rag_explorer.config import reset_settings
    
    # Reset global state
    dependencies._vector_store = None
    dependencies._embedder = None
    dependencies._retrieval_service = None
    reset_settings()
    yield


@pytest.fixture
def temp_persist_dir():
    """Create a temporary directory for ChromaDB."""
    with tempfile.TemporaryDirectory() as tmp_dir:
        yield Path(tmp_dir)


@pytest.fixture
def mock_embedder():
    """Create a mock embedder that returns predictable embeddings."""
    embedder = MagicMock(spec=SentenceTransformerAdapter)
    
    def embed_documents_side_effect(texts):
        # Return one embedding per text
        return [[1.0, 0.0, 0.0, 0.0, 0.0] for _ in texts]
    
    embedder.embed_documents.side_effect = embed_documents_side_effect
    embedder.embed_query.return_value = [1.0, 0.0, 0.0, 0.0, 0.0]
    return embedder


@pytest.fixture
def mock_llm():
    """Create a mock LLM."""
    llm = MagicMock(spec=LangChainLLMAdapter)
    llm.is_available = True
    llm.generate.return_value = "This is a test answer generated by the LLM."
    llm.agenerate.return_value = "This is a test answer generated by the LLM."
    return llm


@pytest.fixture
def mock_reranker():
    """Create a mock reranker."""
    reranker = MagicMock(spec=CrossEncoderReranker)

    def mock_rerank(query, documents, top_n):
        # Just return first top_n documents with a score
        result = []
        for i, doc in enumerate(documents[:top_n]):
            doc_copy = Document(
                page_content=doc.page_content,
                metadata={**doc.metadata, "rerank_score": 0.9 - (i * 0.1)},
            )
            result.append(doc_copy)
        return result

    reranker.rerank.side_effect = mock_rerank
    return reranker


def create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
    """Create a test FastAPI app with mocked dependencies."""
    from ebook_rag_explorer.api import dependencies
    from ebook_rag_explorer.adapters.retrieval.chroma_retriever import ChromaRetriever
    from ebook_rag_explorer.services.retrieval_service import RetrievalService

    settings = Settings(
        chroma_persist_dir=str(temp_persist_dir),
        embedding_model="sentence-transformers/all-MiniLM-L6-v2",
        reranker_model="cross-encoder/ms-marco-MiniLM-L-6-v2",
        llm_provider="openai",
        llm_model="gpt-4o-mini",
        chunk_size=100,
        chunk_overlap=20,
        retrieval_top_k=5,
        rerank_top_n=3,
    )

    # Set up dependencies manually
    vector_store = ChromaAdapter(temp_persist_dir)
    dependencies.set_vector_store(vector_store)
    dependencies.set_embedder(mock_embedder)

    retriever = ChromaRetriever(vector_store, mock_embedder)
    retrieval_service = RetrievalService(
        retriever=retriever,
        reranker=mock_reranker,
        llm=mock_llm,
        retrieval_top_k=5,
        rerank_top_n=3,
    )
    dependencies.set_retrieval_service(retrieval_service)

    app = create_app(settings)
    return app, vector_store


class TestHealthEndpoint:
    """Tests for the health check endpoint."""

    def test_health_check(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test the health check endpoint."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.get("/health")
        assert response.status_code == 200
        assert response.json() == {"status": "healthy"}


class TestIndexEndpoint:
    """Tests for the index endpoint."""

    def test_index_pdf_success(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test successfully indexing a PDF file."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        # Create a simple PDF-like content (mocked)
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book", "author": "Test Author"}
            mock_doc.__len__ = MagicMock(return_value=1)

            mock_page = MagicMock()
            mock_page.get_text.return_value = "This is test content for the PDF."

            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)

            mock_fitz.return_value = mock_doc

            # Create test file
            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy pdf content")

            with open(test_file, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                )

            assert response.status_code == 200, f"Response: {response.text}"
            data = response.json()
            assert data["format"] == "PDF"
            assert data["title"] == "Test Book"
            assert "book_id" in data

    def test_index_unsupported_format(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test indexing an unsupported file format."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.post(
            "/api/index",
            files={"file": ("test.txt", b"some text content", "text/plain")},
        )

        assert response.status_code == 400
        assert "Unsupported file format" in response.json()["detail"]

    def test_index_no_file(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test indexing without a file."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.post("/api/index")
        assert response.status_code == 422  # Validation error


class TestSearchEndpoint:
    """Tests for the search endpoint."""

    def test_search_success(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test successful search."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        # First index a document
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)

            mock_page = MagicMock()
            mock_page.get_text.return_value = "Python programming is great for data science."

            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)

            mock_fitz.return_value = mock_doc

            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy")

            with open(test_file, "rb") as f:
                client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                )

        # Now search
        response = client.post(
            "/api/search",
            json={"query": "What is Python used for?"},
        )

        assert response.status_code == 200
        data = response.json()
        assert "query" in data
        assert "answer" in data
        assert "sources" in data
        assert data["query"] == "What is Python used for?"

    def test_search_empty_query(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test search with empty query fails validation."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.post(
            "/api/search",
            json={"query": ""},
        )

        assert response.status_code == 422  # Validation error


class TestBooksEndpoint:
    """Tests for the books endpoint."""

    def test_list_books_empty(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test listing books when none are indexed."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.get("/api/books")

        assert response.status_code == 200
        assert response.json() == []

    def test_list_books_with_data(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test listing books with indexed content."""
        app, vector_store = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        # Index a document first
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "My Test Book", "author": "Test Author"}
            mock_doc.__len__ = MagicMock(return_value=1)

            mock_page = MagicMock()
            mock_page.get_text.return_value = "Test content."

            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)

            mock_fitz.return_value = mock_doc

            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy")

            with open(test_file, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                )
                assert response.status_code == 200, f"Indexing failed: {response.text}"

        # List books
        response = client.get("/api/books")

        assert response.status_code == 200
        books = response.json()
        assert len(books) == 1
        assert books[0]["title"] == "My Test Book"
        assert books[0]["format"].upper() == "PDF"

    def test_delete_book_not_found(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test deleting a non-existent book."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.delete("/api/books/non-existent-id")

        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()


class TestCollectionsEndpoint:
    """Tests for the collections endpoint."""

    def test_list_collections_empty(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test listing collections when none exist."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.get("/api/collections")

        assert response.status_code == 200
        assert response.json() == []

    def test_list_collections_with_data(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test listing collections with indexed content."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        # Index documents with collection
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)
            mock_page = MagicMock()
            mock_page.get_text.return_value = "Test content."
            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)
            mock_fitz.return_value = mock_doc

            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy")

            with open(test_file, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                    data={"collection_id": "My Collection"},
                )
                assert response.status_code == 200

        # List collections
        response = client.get("/api/collections")

        assert response.status_code == 200
        collections = response.json()
        assert len(collections) == 1
        assert collections[0]["id"] == "my_collection"
        assert collections[0]["name"] == "my_collection"

    def test_delete_collection_not_found(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test deleting a non-existent collection."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        response = client.delete("/api/collections/non-existent")

        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()

    def test_index_with_collection(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test indexing a document with a collection."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)
            mock_page = MagicMock()
            mock_page.get_text.return_value = "Content"
            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)
            mock_fitz.return_value = mock_doc

            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy")

            with open(test_file, "rb") as f:
                response = client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                    data={"collection_id": "TestCollection"},
                )

            assert response.status_code == 200
            # Verify book was indexed with collection
            response = client.get("/api/books")
            books = response.json()
            assert len(books) == 1
            assert books[0]["collection_id"] == "testcollection"

    def test_search_with_collection_filter(self, temp_persist_dir, mock_embedder, mock_llm, mock_reranker):
        """Test searching with collection filter."""
        app, _ = create_test_app_with_deps(temp_persist_dir, mock_embedder, mock_llm, mock_reranker)
        client = TestClient(app)
        
        # Index document to collection
        with patch("ebook_rag_explorer.adapters.parsers.pdf_parser.fitz.open") as mock_fitz:
            mock_doc = MagicMock()
            mock_doc.metadata = {"title": "Test Book"}
            mock_doc.__len__ = MagicMock(return_value=1)
            mock_page = MagicMock()
            mock_page.get_text.return_value = "Python programming content"
            mock_doc.__enter__ = MagicMock(return_value=mock_doc)
            mock_doc.__exit__ = MagicMock(return_value=False)
            mock_doc.__getitem__ = MagicMock(return_value=mock_page)
            mock_fitz.return_value = mock_doc

            test_file = temp_persist_dir / "test.pdf"
            test_file.write_text("dummy")

            with open(test_file, "rb") as f:
                client.post(
                    "/api/index",
                    files={"file": ("test.pdf", f, "application/pdf")},
                    data={"collection_id": "PythonCollection"},
                )

        # Search within collection
        response = client.post(
            "/api/search",
            json={"query": "What is this about?", "collection_id": "PythonCollection"},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["query"] == "What is this about?"
